### ISSUE TITLE
pip install -r requirements.txt gives an error on logparser

### ISSUE THREAD

**Issue by smccarthy** [mozilla/autophone#13]
Downloading/unpacking logparser (from -r requirements.txt (line 4))
  Could not find any downloads that satisfy the requirement logparser (from -r requirements.txt (line 4))
Cleaning up...
No distributions at all found for logparser (from -r requirements.txt (line 4))
Storing debug log for failure in /Users/shawn.mccarthy/.pip/pip.log

**Comment by nabinkhadka** [comment]
@smccarthy Does this still exist on your end?

**Comment by smccarthy** [comment]
I just tried it, and it worked (when I used pip 9.0.1 and python 2.7). This can be closed.
