### ISSUE TITLE
bad testroot

### ISSUE THREAD

**Issue by markrcote** [mozilla/autophone#5]
Somehow this happened:

$ ls -l /data/data/com.mozilla.SUTAgentAndroid/files/
-rw------- app_113  app_113               102 2012-04-07 11:27 SUTAgent.ini
drwx------ app_113  app_113                     2012-04-07 11:27 tests

Since the tests directory somehow became accessible only to the app_113 user, the shell command to launch runbrowserprofile.sh failed:

$ sh /data/data/com.mozilla.SUTAgentAndroid/files/tests/autophone/runbrowserprofile.sh org.mozilla.fennec/.App /data/data/com.mozilla.SUTAgentAndroid/files/tests/autophone/profile file://mnt/sdcard/s1test/startup6.html
sh: Can't open /data/data/com.mozilla.SUTAgentAndroid/files/tests/autophone/runbrowserprofile.sh

Unfortunately autophone didn't notice this error (see issue #2).

**Comment by bclary** [comment]
This project is no longer active and is being archived.
