### ISSUE TITLE
Update treeherder-client from 3.1.0 to 4.0.0

### ISSUE THREAD

**Issue by edmorley** [mozilla/autophone#61]
Please can you update [treeherder-client](https://pypi.python.org/pypi/treeherder-client) to the latest release (4.0.0) to pick up changes to which API endpoints are used (the old endpoints will be disabled at some point in the future):
https://github.com/mozilla/autophone/blob/d7e3e06f02aa5f8be12f7a3a648f8710f5b5bade/requirements.txt#L1

The changelog can be found here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1387711#c2

Many thanks!

**Comment by bclary** [comment]
This project is no longer active and is being archived.
