### ISSUE TITLE
Use pyup.io to keep Python dependencies up to date

### ISSUE THREAD

**Issue by edmorley** [mozilla/autophone#62]
Several Mozilla projects now use https://pyup.io/ to automatically open PRs when their Python packages have new releases available. Perhaps it's a good fit for this project too?

Search for "pyup" in this guide for more info:
https://wiki.mozilla.org/Security/FirefoxOperations#Security_Checklist

(Context: keeping the treeherder-client package up to date to help the Treeherder team deprecate API features more expediently)

Many thanks!

**Comment by bclary** [comment]
This project is no longer active and is being archived.
